name: Bug Report
description: File a bug report
labels: bug, not confirmed
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a crash here, please make sure you are on the latest version of Nanaica.
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Nanaica version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
       [23:54:45 INFO]: Checking version, please wait...
[23:54:46 INFO]: Current: git-Nanaica-"57861d6" (MC: 1.20.2)*
        </details>
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Nanaica from [here](https://github.com/NanaicaMC/Nanaica/releases/latest).
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: My version of Minecraft is supported by Nanaica.
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
