blank_issues_enabled: true
contact_links:
  - name: Nanaica Discord
    url: https://discord.nanaicamc.tk
    about: If you are having issues, come ask us on our Discord server!
  - name: Ask Community
    url: https://github.com/NanaicaMC/Nanaica/discussions
    about: If you have a question, ask the community on the discussion page!
  - name: Nanaica Docs
    url: https://docs.nanaicamc.tk
    about: You can find some Q&A at our Nanaica docs
